### ISSUE TITLE
Instances that are still untranslated to Spanish

### ISSUE THREAD

**Issue by rasec70** [frappe/translator#104]
School Setting section still unstranslated to Spanish.
![untraslated](https://cloud.githubusercontent.com/assets/18291208/25726031/7e092aaa-30df-11e7-817d-c645d1e58819.png)

**Comment by mbauskar** [comment]
@rasec70,

Schools Setting Sections are now translated.

<img width="947" alt="screen shot 2017-09-11 at 10 28 39 am" src="https://user-images.githubusercontent.com/11224291/30259038-0150bd80-96dc-11e7-80cb-4fe80a0a25bd.png">
