### ISSUE TITLE
New Language - K'iche'  or Quiché

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/translator#124]
This language's [ISO 639-3 Code](https://en.wikipedia.org/wiki/ISO_639:quc): _quc_
There is NO ISO 639-1 Code, thus it should have to be enabled

[Summer Institute of Linguistics, Inc.](http://www-01.sil.org/iso639-3/documentation.asp?id=quc)
[Ethnologue - K'iche'](https://www.ethnologue.com/language/quc)

This language is rated at a level 4 in Ethnologue, which by their description says:

> The EGIDS level for this language in its primary country is 4 (Educational) — The language is in vigorous use, with standardization and literature being sustained through a widespread system of institutionally supported education.

This language is classified as **Purple**, which means:

> Purple = Institutional (EGIDS 0-4) — The language has been developed to the point that it is used and sustained by institutions beyond the home and community.

Thus, having this language in ERPNext would help immensely in its growth and input.

**Comment by codingCoffee** [comment]
https://translate.erpnext.com/view?lang=quc

**Comment by Tropicalrambler** [comment]
Thanks! @codingCoffee
