### ISSUE TITLE
Portal letter selector is missing

### ISSUE THREAD

**Issue by fproldan** [frappe/translator#125]
Hi! It's seems there is an issue with momentjs that prevent the letter selector works.

Thanks

![captura de pantalla 2018-02-27 a la s 18 53 36](https://user-images.githubusercontent.com/4945122/36757139-8ec1002e-1bef-11e8-8943-239ae55c421a.png)

**Comment by achillesrasquinha** [comment]
Fixed. Please Confirm

**Comment by krnkris** [comment]
Fixed by @achillesrasquinha 

THX.

**Comment by achillesrasquinha** [comment]
Welcome yo!
