### ISSUE TITLE
impossible to edit/verify/find in Translator

### ISSUE THREAD

**Issue by epe** [frappe/translator#127]
I am logged in and have selected German Language. 
https://translate.erpnext.com/view?lang=de

If I click verify  at an item  - nothing ever happens.
I can find items in the page, but I cannot find some terms that need correction. 
 e.g. Chapter "Kapitel" should really be translated Regionalgruppe.
Also the search feature doesnt work, nor the field Items starting with [* ] could be changed.
The whole page seems completely static - do I have to be given rights to translate?

**Comment by epe** [comment]
Any idea how I could actually help translating?

**Comment by BartoszBorowicz** [comment]
I can not edit any translation too.
Tommorow i was going to translate some pl 
is it possible it will work by then ?

**Comment by epe** [comment]
Where do all the translations come from? 
e.g. In Print Formats "Letter" is translated to de "Brief" but should really be "Letter" in this instance because we mean the page format, not a Letter someone can write. 
Well, I can translate terms in my own instance, but it should really be as easy to translate for everyone!

**Comment by epe** [comment]
@rmehta  how could help with that? Here's some people willing to help translate!

**Comment by yeisonvargasf** [comment]
@rmehta @nabinhait @netchampfaris I would like contribute to Spanish and Spanish CO translations but seems that https://translate.erpnext.com has a bug, because clicking over the message to edit doesn't work, nothing happen. Please could you help me?

Chrome console show this error on page reload:

`pretty_date.js:7`

```Uncaught ReferenceError: moment is not defined
    at u (pretty_date.js:7)
    at window.comment_when (pretty_date.js:68)
    at HTMLSpanElement.<anonymous> (view?lang=en-US:197)
    at Function.each (jquery.min.js:2)
    at n.fn.init.each (jquery.min.js:2)
    at view?lang=en-US:194
    at website.js:274
    at Array.forEach (<anonymous>)
    at Object.trigger_ready (website.js:273)
    at HTMLDocument.<anonymous> (website.js:420)```

**Comment by achillesrasquinha** [comment]
Hello, can you please confirm on this now?

**Comment by epe** [comment]
Hi Achilles, 
First, i see this huge bar now. Wow! Ok, so its now possible to slide the bar and get to the corresponding Terms. I can verify unverified translated Terms.

What I cant see yet is how to edit the translation of a term? do I need to be approved as a user? 

thanks!

**Comment by achillesrasquinha** [comment]
Yes you might have to.

**Comment by yeisonvargasf** [comment]
thanks @achillesrasquinha, It's works!

**Comment by yeisonvargasf** [comment]
@epe could you close the issue?

**Comment by epe** [comment]
Its getting OT now, but how do I get allowed to actually translate terms? 
https://translate.erpnext.com/help  doesnt mention if/how someone needs to apply to be able to make translations. 
cheers!

**Comment by yeisonvargasf** [comment]
@epe For translate/edit verified terms we need al least 100 Points of Karma, We only can verify terms in the  meantime.

With not verified terms, double click over message and edit it.


![translation](https://user-images.githubusercontent.com/18555394/37645443-dd1c9d36-2bf4-11e8-89f1-473958983098.png)

**Comment by achillesrasquinha** [comment]
Hi, in case of some issues, feel free to get in touch :wink:

**Comment by krnkris** [comment]
It works by now.

Please close this subject.

**Comment by yeisonvargasf** [comment]
@achillesrasquinha thanks!

**Comment by epe** [comment]
Ok, thanks @achillesrasquinha
