### ISSUE TITLE
html chars < and > not escaped as &lt; or &gt;

### ISSUE THREAD

**Issue by krawalli** [frappe/translator#15]
while verifing i got a english string

"Add code as &lt;script&gt;"

but the &lt; char seems not to be escaped for editing, since in the input box for translation some html from the webpage itself is shown:

"Code als  hinzfügen
	&lt;/div&gt;
	&lt;div class="col-sm-2"&gt;
		....."

![image](https://cloud.githubusercontent.com/assets/1234639/5142000/2b43b4a8-717d-11e4-8ef6-85fb74c2b1e3.png)

So maybe next lines for letter "A" below that entry are not shown - if there are some

See yourself at:
https://frappe.io/translator/view?lang=de

**Comment by rmehta** [comment]
Fixed HTML strings.
