### ISSUE TITLE
When english phrase contains <script>, translation goes boom

### ISSUE THREAD

**Issue by gentle-** [frappe/translator#25]
for example here: https://translate.erpnext.com/translator/view?c=A&lang=nl
The last entry is
    ```Add code as <script> ```
The translation is gibberish, but that's because the page fails to function properly after this point (it's obvious that this phrase is not supposed to be the last phrase in the A-section).

**Comment by gentle-** [comment]
reopen please, as this issue is not solved (or it's not live on translate.erpnext.com)
![selection_018](https://cloud.githubusercontent.com/assets/10958563/6543027/9f2ececa-c50b-11e4-89e7-b5bf33b67a36.png)

**Comment by pdvyas** [comment]
fixed yesterday, can you check?

**Comment by gentle-** [comment]
Yep, it is fixed now. Thanks @pdvyas
