### ISSUE TITLE
My profile in Translator is display as someone else

### ISSUE THREAD

**Issue by dofrance** [frappe/translator#29]
User profile not work, after sign in, my name display as Christian Barraud, can't reset password too when I sign in using my Gg acc

**Comment by pdvyas** [comment]
what is your username?

**Comment by dofrance** [comment]
it's is: billyduc1987@gmail.com

**Comment by pdvyas** [comment]
can you check now? Try resetting password or using github/google sign in.

**Comment by dofrance** [comment]
yes it work now!
