### ISSUE TITLE
Tibetan

### ISSUE THREAD

**Issue by netevent** [frappe/translator#36]
Hi, I am setting up erpnext in a textile manufacturing business in Tibet, we would like to translate erpnext into tibetan, please add the language and we will start translating the elements

**Comment by netevent** [comment]
hi can anyone help me with this ? we want to get started translating the elemetns asap

thanks

**Comment by pdvyas** [comment]
Will not be able to bootstrap via google translate. Can you post the exact name of the language (in the language) and ISO 639-1 code?

**Comment by netevent** [comment]
Hi ok
It's 
ISO 639-1
bo	
http://en.m.wikipedia.org/wiki/Standard_Tibetan

ལྷ་སའི་སྐད་

----------------------
Michael Kelly-Gleeson
0419 146618
http://netevent.net.au

**Comment by netevent** [comment]
Hi How did you go with adding tibetan language as we are keen to start
translating

thanks

Michael

------------------------------
Michael Kelly-Gleeson
0419 146618
http://netevent.net.au

**Comment by rmehta** [comment]
Added via frappe/erpnext#3791

There are no translations though, you can start adding via https://translate.erpnext.com/view?lang=bo
