### ISSUE TITLE
New Language - ALBANIAN

### ISSUE THREAD

**Issue by macroplus** [frappe/translator#38]
Hi I want to start a Translation for the  Albanian Language of ERPNext
ISO Codes
639-1 639-2   639-2b     639-3
sq	   sqi	        alb  	       sqi + 4

**Comment by macroplus** [comment]
HI i am setting up ERPNext for a business in Kosovo and We would need the Albanian Translation ASAP. Can anybody please open up a new Language in the translator so i can start translating the elements.

**Comment by macroplus** [comment]
Ok it seems ill translate the CSV files in the project and add a new language manually.

**Comment by rmehta** [comment]
Added via frappe/erpnext#3791
