### ISSUE TITLE
Malay (Malaysia) ms ms-my

### ISSUE THREAD

**Issue by mridzuan** [frappe/translator#41]
Please create a new translation link for malay language, specifically malay-malaysia. I'll help in the translation, where ever I can.

**Comment by rmehta** [comment]
There is already a language for ms, is ms-my different?

**Comment by mridzuan** [comment]
Nope, I got it wrong. I've worked a bit on the translation. Got to find
another guy to verify.

**Comment by rmehta** [comment]
Added via frappe/erpnext#3791
