### ISSUE TITLE
New Language - Slovenian

### ISSUE THREAD

**Issue by sp9leo** [frappe/translator#59]
A week or two ago I started translating Slovenian language on translate.erpnext.com.
Why has it been removed?

**Comment by anandpdoshi** [comment]
Are you looking for this: https://translate.erpnext.com/view?lang=sk <https://translate.erpnext.com/view?lang=sk>

Best,
Anand Doshi

ERPNext

**Comment by sp9leo** [comment]
Nope. That is "slovenčina" which is Slovak language. Country=Slovakia Country code Sk_sk
I'm looking for "slovenščina" which is Slovenian lanugage. Country=Slovenia. Country code sl_si.
They are commonly confused so maybe it was removed as a duplicate entry.

best regards
Leo
