### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by MaxMorais** [frappe/translator#61]
Hi all, I'm trying to lead the translations to a more friendly translation to Brazilian Portuguese, but I'm getting the error in the title after try edit a list of entries.

![captura de tela de 2015-11-28 15 43 45](https://cloud.githubusercontent.com/assets/1288676/11453165/31651cde-95e7-11e5-909d-531adf72e92c.png)

![download](https://cloud.githubusercontent.com/assets/1288676/11453164/3161e154-95e7-11e5-9531-9987ede2bbc4.png)

**Comment by rmehta** [comment]
Does it clear after refresh?

**Comment by MaxMorais** [comment]
No still after the refresh!

**Comment by rmehta** [comment]
Weird, happens intermittently... its been a while since I have seen this code!

**Comment by rmehta** [comment]
Fixed now. Check
