### ISSUE TITLE
Gujarati

### ISSUE THREAD

**Issue by rashmimacwan** [frappe/translator#63]
Please add Gujarati

**Comment by anandpdoshi** [comment]
@rashmimacwan the gujarati translations from google aren't so good. Can you help us translate? https://translate.erpnext.com/view?lang=gu

**Comment by rashmimacwan** [comment]
Dear Anand
I love to help you. Right now my schedule is tight, if this is urgent then
I can Translate as a paid job. Let me know what you think.
Regards
Rashmi Macwan
