### ISSUE TITLE
New Language - US English

### ISSUE THREAD

**Issue by busyfritz** [frappe/translator#67]
I would really like to help with a true US English translation with typical US accounting terms. Example: vendors instead of suppliers, Check instead of Cheque etc. And also to fix various grammatical issues such as pluralization. I would be willing to provide much of the work. I think this would be a great benefit to ERPnext in giving it a more polished feel! I not sure how to go about doing the split between the two.

**Comment by rmehta** [comment]
:+1:

**Comment by busyfritz** [comment]
Quick question, is there a language code for this or what do I need to do to get started?

**Comment by rmehta** [comment]
we will have to add it manually in the translation portal. Will try and do this next week. Thanks!

**Comment by rmehta** [comment]
Added (sorry took a lot longer than that!)
