### ISSUE TITLE
New Language - Montenegro

### ISSUE THREAD

**Issue by vladucoju** [frappe/translator#68]
Hello, 

i am new to ERPNEXT and i wan't to translate our local language Montenegro (Crnogorski MNE). He is similar to Serbian and Croatian. Serbian has cirilic writing, and we use latin. If it be posible to convert Serbian to latin, it will be easy for me to make a translation.
Thanks in advance.

**Comment by vladucoju** [comment]
Serbian, croatian and bosnian language are similar to Montenegro, but they don't have good translation. They used Google translation to do this. It is not intuitive. I am planning to translate Montenegro language manually, and after i finish it you could copy that translation to above mentioned lanuages.

**Comment by rmehta** [comment]
What is the language code? Unable to find in Wikipedia. Google Translate does not recognize `mis`

**Comment by rmehta** [comment]
#82  is this the same?

**Comment by yashodhank** [comment]
For Reference: https://en.wikipedia.org/wiki/Montenegrin_language
Does not have ISO / Language codes.

**Comment by vladucoju** [comment]
Hello @rmehta  , thank you for answering. #82 is the same thing. @yashodhank is right. It is the same language family. The language code is "Montenegro - Serbian (Latin)",    "sr-ME". Language tag is ME. You could add Serbian latin. You already add Serbian cyrilic for Serbia.

**Comment by vladucoju** [comment]
Thanks for adding serbian latin language.
