### ISSUE TITLE
New Currency- Afghani (AFN)

### ISSUE THREAD

**Issue by smayar** [frappe/translator#70]
The afghani (sign: Afs; Pashto: افغانۍ; Dari افغانی; code: AFN) is the currency of Afghanistan. It is nominally subdivided into 100 pul (پول), although there are no pul coins currently in circulation.
For more information visit this link: https://en.wikipedia.org/wiki/Afghan_afghani 
Kindly request you to add this currency in list of currencies which select able during installation setup.

**Comment by rmehta** [comment]
Added

**Comment by smayar** [comment]
Thank you Mehta

**Comment by smayar** [comment]
![setup-wizard](https://cloud.githubusercontent.com/assets/8857846/18025695/2494615e-6c47-11e6-91e1-fbaad2f12b47.PNG)

@rmehta today i have try new installation but still not see Afghanistan currency in setup-wizard

**Comment by rmehta** [comment]
Will come in 7.1

**Comment by smayar** [comment]
OK thanks for update
