### ISSUE TITLE
Downloaded translations not working

### ISSUE THREAD

**Issue by applepipe** [frappe/translator#89]
I'm translating to pt_BR and always used the files downloaded from https://translate.erpnext.com/download to test, but since the last modification in translations it doesnt work anymore, seems like the file downloaded is incomplete.

**Comment by rmehta** [comment]
@applepipe common translations will be picked from pt.csv, so you will have to update pt-BR.csv on top of pt.csv

**Comment by applepipe** [comment]
I've tried to make a symbolic link and copied pt-BR.csv to pt.csv, same result, the past 2 months I dedicated to it I only used pt-BR files.

**Comment by applepipe** [comment]
I think I need more info, can´t get it to work

**Comment by applepipe** [comment]
@rmehta I think I need more info, can´t get it to work

**Comment by rmehta** [comment]
Why don't you try downloading both the `pt` and `pt-BR` files and check.

**Comment by applepipe** [comment]
@rmehta tried again and had the same result, I think I found the problem, the files downloaded from the server are incomplete or corrupted. I made all the translations on the portal and made a simple script to download updates on every bench update, but somehow the file downloaded now has half of the size of my backup (a month old), I believe there is something to do with the file generated in the portal.

Restoring an old csv file worked on master branch, put on develop its still in english.

**Comment by rmehta** [comment]
https://github.com/frappe/frappe/blob/develop/frappe/translate.py#L206

**Comment by applepipe** [comment]
@rmehta 

Downloaded again pt.csv and pt-BR.csv from https://translate.erpnext.com/download

![print_0](https://cloud.githubusercontent.com/assets/18335894/18130571/e07ff5ba-6f65-11e6-92de-e073a41ce79c.png)

![print_1](https://cloud.githubusercontent.com/assets/18335894/18130570/e05d72b0-6f65-11e6-996a-9585e550d765.png)

The same occurs with the original files, fresh installation.

Every language I select with '-' is not working, zh-TW, es-MX, pt-BR... if I select the parent it loads normally (es, pt, zh), but when I select pt-BR it just loads everything in english.

**Comment by rmehta** [comment]
@applepipe thank fixed!
