### ISSUE TITLE
Spanish (Dominican Republic)

### ISSUE THREAD

**Issue by YefriTavarez** [frappe/translator#96]
I would like to help with some enhancements in the Spanish Language in general that will apply for Spanish in Dominican Republic. I don't know if they would apply to some other language, but I can help with mines, the one that we speak in the Dominican Republic.

**Comment by yashodhank** [comment]
@YefriTavarez > Translation Portal: https://translate.erpnext.com

Kindly add
Dominican Spanish
Language Code: es-DO

**Comment by mbauskar** [comment]
duplicate https://github.com/frappe/translator/issues/101
