### ISSUE TITLE
Discount Amount  not properly translated in French

### ISSUE THREAD

**Issue by chdecultot** [frappe/translator#97]
Hi Everyone,

The below translation is incorrect and appears as is on the invoice. Can it please be modified as it is blocking for a client ?

Sorry I accidentally clicked on the "validated" button and doesn't find how to undo it. Therefore I don't have enough Karma Points to edit the translation. It may cause some confusion... 

Actual and incorrect translation
Discount Amount = S'il vous plaît tirer des articles de livraison Note

Correct translation to be updated
Discount Amount = Remise

Thanks a lot for your help.

Best regards,
Charles-Henri

**Comment by yashodhank** [comment]
Discount Amount
![image](https://cloud.githubusercontent.com/assets/1083792/22239231/8f3fe68a-e23b-11e6-98a5-ead6b62a2438.png)

**Comment by chdecultot** [comment]
Hi @yashodhank 

Sorry if I was not clear enough, this translation is incorrect.

Instead it needs to be: "Remise"

Thanks!

**Comment by chdecultot** [comment]
I finally got enough "Karma points" on translate.erpnext.com to modify it.
Thanks
